# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spvault.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spvault.proto',
  package='spvault',
  syntax='proto3',
  serialized_options=b'Z\007./proto\252\002\007SPVault',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rspvault.proto\x12\x07spvault\"X\n\x0b\x41uthRequest\x12\x0f\n\x07siteUrl\x18\x01 \x01(\t\x12#\n\x08strategy\x18\x02 \x01(\x0e\x32\x11.spvault.Strategy\x12\x13\n\x0b\x63redentials\x18\x03 \x01(\t\"$\n\x10TokenAuthRequest\x12\x10\n\x08regToken\x18\x01 \x01(\t\"U\n\tAuthReply\x12\r\n\x05token\x18\x01 \x01(\t\x12%\n\ttokenType\x18\x02 \x01(\x0e\x32\x12.spvault.TokenType\x12\x12\n\nexpiration\x18\x03 \x01(\x03\"I\n\nRegRequest\x12)\n\x0b\x61uthRequest\x18\x01 \x01(\x0b\x32\x14.spvault.AuthRequest\x12\x10\n\x08regToken\x18\x02 \x01(\t\"\x1c\n\x08RegReply\x12\x10\n\x08regToken\x18\x01 \x01(\t\" \n\x0c\x44\x65RegRequest\x12\x10\n\x08regToken\x18\x01 \x01(\t\"\x07\n\x05\x45mpty*;\n\x08Strategy\x12\t\n\x05\x61\x64\x64in\x10\x00\x12\x08\n\x04\x61\x64\x66s\x10\x01\x12\x07\n\x03\x66\x62\x61\x10\x02\x12\x08\n\x04saml\x10\x03\x12\x07\n\x03tmg\x10\x04*/\n\tTokenType\x12\n\n\x06\x42\x65\x61rer\x10\x00\x12\n\n\x06\x43ookie\x10\x01\x12\n\n\x06\x43ustom\x10\x03\x32\x83\x02\n\x05Vault\x12\x43\n\x15\x41uthenticateWithCreds\x12\x14.spvault.AuthRequest\x1a\x12.spvault.AuthReply\"\x00\x12H\n\x15\x41uthenticateWithToken\x12\x19.spvault.TokenAuthRequest\x1a\x12.spvault.AuthReply\"\x00\x12\x34\n\x08Register\x12\x13.spvault.RegRequest\x1a\x11.spvault.RegReply\"\x00\x12\x35\n\nDeRegister\x12\x15.spvault.DeRegRequest\x1a\x0e.spvault.Empty\"\x00\x42\x13Z\x07./proto\xaa\x02\x07SPVaultb\x06proto3'
)

_STRATEGY = _descriptor.EnumDescriptor(
  name='Strategy',
  full_name='spvault.Strategy',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='addin', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='adfs', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='fba', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='saml', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='tmg', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=389,
  serialized_end=448,
)
_sym_db.RegisterEnumDescriptor(_STRATEGY)

Strategy = enum_type_wrapper.EnumTypeWrapper(_STRATEGY)
_TOKENTYPE = _descriptor.EnumDescriptor(
  name='TokenType',
  full_name='spvault.TokenType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Bearer', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Cookie', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Custom', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=450,
  serialized_end=497,
)
_sym_db.RegisterEnumDescriptor(_TOKENTYPE)

TokenType = enum_type_wrapper.EnumTypeWrapper(_TOKENTYPE)
addin = 0
adfs = 1
fba = 2
saml = 3
tmg = 4
Bearer = 0
Cookie = 1
Custom = 3



_AUTHREQUEST = _descriptor.Descriptor(
  name='AuthRequest',
  full_name='spvault.AuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='siteUrl', full_name='spvault.AuthRequest.siteUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='spvault.AuthRequest.strategy', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credentials', full_name='spvault.AuthRequest.credentials', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=114,
)


_TOKENAUTHREQUEST = _descriptor.Descriptor(
  name='TokenAuthRequest',
  full_name='spvault.TokenAuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regToken', full_name='spvault.TokenAuthRequest.regToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=152,
)


_AUTHREPLY = _descriptor.Descriptor(
  name='AuthReply',
  full_name='spvault.AuthReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='spvault.AuthReply.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokenType', full_name='spvault.AuthReply.tokenType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='spvault.AuthReply.expiration', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=239,
)


_REGREQUEST = _descriptor.Descriptor(
  name='RegRequest',
  full_name='spvault.RegRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authRequest', full_name='spvault.RegRequest.authRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regToken', full_name='spvault.RegRequest.regToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=314,
)


_REGREPLY = _descriptor.Descriptor(
  name='RegReply',
  full_name='spvault.RegReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regToken', full_name='spvault.RegReply.regToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=344,
)


_DEREGREQUEST = _descriptor.Descriptor(
  name='DeRegRequest',
  full_name='spvault.DeRegRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regToken', full_name='spvault.DeRegRequest.regToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=378,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='spvault.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=387,
)

_AUTHREQUEST.fields_by_name['strategy'].enum_type = _STRATEGY
_AUTHREPLY.fields_by_name['tokenType'].enum_type = _TOKENTYPE
_REGREQUEST.fields_by_name['authRequest'].message_type = _AUTHREQUEST
DESCRIPTOR.message_types_by_name['AuthRequest'] = _AUTHREQUEST
DESCRIPTOR.message_types_by_name['TokenAuthRequest'] = _TOKENAUTHREQUEST
DESCRIPTOR.message_types_by_name['AuthReply'] = _AUTHREPLY
DESCRIPTOR.message_types_by_name['RegRequest'] = _REGREQUEST
DESCRIPTOR.message_types_by_name['RegReply'] = _REGREPLY
DESCRIPTOR.message_types_by_name['DeRegRequest'] = _DEREGREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.enum_types_by_name['Strategy'] = _STRATEGY
DESCRIPTOR.enum_types_by_name['TokenType'] = _TOKENTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHREQUEST,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.AuthRequest)
  })
_sym_db.RegisterMessage(AuthRequest)

TokenAuthRequest = _reflection.GeneratedProtocolMessageType('TokenAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENAUTHREQUEST,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.TokenAuthRequest)
  })
_sym_db.RegisterMessage(TokenAuthRequest)

AuthReply = _reflection.GeneratedProtocolMessageType('AuthReply', (_message.Message,), {
  'DESCRIPTOR' : _AUTHREPLY,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.AuthReply)
  })
_sym_db.RegisterMessage(AuthReply)

RegRequest = _reflection.GeneratedProtocolMessageType('RegRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGREQUEST,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.RegRequest)
  })
_sym_db.RegisterMessage(RegRequest)

RegReply = _reflection.GeneratedProtocolMessageType('RegReply', (_message.Message,), {
  'DESCRIPTOR' : _REGREPLY,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.RegReply)
  })
_sym_db.RegisterMessage(RegReply)

DeRegRequest = _reflection.GeneratedProtocolMessageType('DeRegRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEREGREQUEST,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.DeRegRequest)
  })
_sym_db.RegisterMessage(DeRegRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'spvault_pb2'
  # @@protoc_insertion_point(class_scope:spvault.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_VAULT = _descriptor.ServiceDescriptor(
  name='Vault',
  full_name='spvault.Vault',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=500,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='AuthenticateWithCreds',
    full_name='spvault.Vault.AuthenticateWithCreds',
    index=0,
    containing_service=None,
    input_type=_AUTHREQUEST,
    output_type=_AUTHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AuthenticateWithToken',
    full_name='spvault.Vault.AuthenticateWithToken',
    index=1,
    containing_service=None,
    input_type=_TOKENAUTHREQUEST,
    output_type=_AUTHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='spvault.Vault.Register',
    index=2,
    containing_service=None,
    input_type=_REGREQUEST,
    output_type=_REGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeRegister',
    full_name='spvault.Vault.DeRegister',
    index=3,
    containing_service=None,
    input_type=_DEREGREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VAULT)

DESCRIPTOR.services_by_name['Vault'] = _VAULT

# @@protoc_insertion_point(module_scope)
