# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: spvault.proto for package 'spvault'

require 'grpc'
require 'spvault_pb'

module Spvault
  module Vault
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'spvault.Vault'

      rpc :AuthenticateWithCreds, ::Spvault::AuthRequest, ::Spvault::AuthReply
      rpc :AuthenticateWithToken, ::Spvault::TokenAuthRequest, ::Spvault::AuthReply
      rpc :Register, ::Spvault::RegRequest, ::Spvault::RegReply
      rpc :DeRegister, ::Spvault::DeRegRequest, ::Spvault::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
